### ISSUE TITLE
Get cart item API, if no item found in customer profile cart. Message should appear.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#13] opened 2022-11-30 11:17 UTC
**Bagisto - MASTER
Bagisto Rest API - MASTER
Description**
When we check the API after customer authorisation and we check the Cart items related information, if there is no product in the cart added in the customer profile, then there we can see No message appears in the Postman response.

**Steps to Reproduce**
**1.** Go to Postman -> Shop -> Customers -> Cart -> Get Cart Items -> Now check the response.
**2.** There we can see null data but no message. Here message need to be added.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-11-30 16-45-25](https://user-images.githubusercontent.com/92721837/204782664-486c5694-ed2c-4e1c-9f06-32f0da3120be.png)

**Expected Result**

If there are no address in the customer profile, In postman response we can add message.
**Message - No Items Found**

**Comment by Amitk-webkul** [comment] 2023-05-16 13:54
The issue is fixed. [Here](https://tinyurl.com/2m6uvewb)

**Comment by vivek-webkul** [comment] 2023-05-18 10:21
Closing this issue as invalid.

**Closed by vivek-webkul** 2023-05-18 10:21 UTC
Labels: Update Message, fixed
