### ISSUE TITLE
In Admin Login API - Device Name should not  be a mandatory field.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#28] opened 2022-12-06 08:24 UTC
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
In **postman**, when we try to login as **admin**, there in form data **device name** is a **mandatory** field.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto -> Admin -> User -> Auth Routes
**2.** Now try to login without the device_name.
**3.** We are unable to login without this.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/205858531-ff73882b-7505-47f9-b5b1-2f7301dbbef1.mp4

**Expected Result**

This is not a  **mandatory** field and hence we should be able to **Login** the **Admin**.

**Comment by Amitk-webkul** [comment] 2023-05-16 13:46
The issue is working fine for the admin log-in API.[Here](https://tinyurl.com/2k5uanus)

**Comment by vivek-webkul** [comment] 2023-05-18 10:25
Closing this issue as Invalid.

**Closed by vivek-webkul** 2023-05-18 10:25 UTC
Labels: bug, fixed
