### ISSUE TITLE
In Mass Delete CMS API - We are unable to delete the CMS Pages.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#31] opened 2022-12-08 04:43 UTC
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we are trying to delete the CMS Pages in Mass, there we are facing some issue. In form data when we pass the data in Array format, it is showing the issue, either numerical or comma values to be enter and if we do so, it is facing the issue of string data.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto - > Admin -> CMS
**2.** There when we pass the data in raw and form form format. We found the issue.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-08 10-02-02](https://user-images.githubusercontent.com/92721837/206358377-44fa4073-0a47-40ab-9af6-29e09e1f4f6e.png)
![Screenshot from 2022-12-08 10-02-11](https://user-images.githubusercontent.com/92721837/206358385-4138bede-4612-41b6-a4fe-ac5d6bb02ef8.png)
![Screenshot from 2022-12-08 10-02-42](https://user-images.githubusercontent.com/92721837/206358391-64767dc5-e2d1-49bc-9dd2-4ba8194e70c5.png)

**Expected Result**
Please check the concern, and with mass data we should be able to Fetch the information and we should be able to delete in mass.

**Comment by Amitk-webkul** [comment] 2023-05-16 13:32
The issue is fixed.[Here](https://tinyurl.com/2rydxtxc)

**Comment by Komal-sharma-2712** [comment] 2024-01-10 09:52
I have checked this issue has been fixed at this moment:

![Screenshot from 2024-01-10 15-22-26](https://github.com/bagisto/rest-api/assets/63539748/87eb6019-3492-4e22-97b5-8328ff904a99)


So, I am closing this issue.

**Closed by Komal-sharma-2712** 2024-01-10 09:52 UTC
Labels: Bug, Fixed
