### ISSUE TITLE
Add and Remove Product from wish list - Data should show the remaining products in the wish list after removing product.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#8] opened 2022-11-30 06:06 UTC
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we add **different products** in the **wishlist** with the help of **API**, then we check the details we are able to see the **products added in wishlist**, after that when we remove any **1 wishlist product** and check the  response, there we can see that the data is showing **null** **response**.

Product is removed from the wishlist.

**Steps to Reproduce**
**1.** Go to Postman -> Add or Remove Product -> Add different product -> Now remove any one product.
**2.** In response check the data is showing null as a result.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/204720188-56393726-3290-444c-9bea-58fba08e9b82.mp4

**Expected Result**

Here what we can do is that we can show the **product count** which are **present** in the **wishlist**. As we can see the wishlist products in Get all product ID.

**Comment by Amitk-webkul** [comment] 2023-05-16 14:04
The issue is fixed.

**Comment by vivek-webkul** [comment] 2023-05-18 10:17
Closing this issue merged in PR #48

**Closed by vivek-webkul** 2023-05-18 10:17 UTC
Labels: bug, fixed
