### ISSUE TITLE
In Mass Delete - Header Content API, we are unable to delete the Header Content.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/rest-api#33] opened 2022-12-08 07:25 UTC
**Bagisto - MASTER**
**Bagisto Rest API - MASTER**
**Description**
When we try to delete the Header content in mass delete API, we are unable to delete it.

**Steps to Reproduce**
**1.** Go to Postman -> Bagisto -> Admin -> Velocity -> Header Content -> Mass Delete Header Content
**2.** Here when we pass the data we are facing the issue.

**Actual Result**
Please check the screenshot/video for a better understanding of the issue.

**Video/Screenshot**
![Screenshot from 2022-12-08 12-49-10](https://user-images.githubusercontent.com/92721837/206384639-07536443-a2dd-43ed-8166-e8be3aa4d30f.png)

**Expected Result**
We should be able to mass delete the Header content.

**Comment by Amitk-webkul** [comment] 2023-05-16 13:24
@Aqib-Webkul 
The issue is fixed. [Here](https://tinyurl.com/2ely7c7k)

**Comment by Komal-sharma-2712** [comment] 2024-01-10 09:54
This option is not available velocity option, so closing this issue.

**Closed by Komal-sharma-2712** 2024-01-10 09:54 UTC
Labels: Bug, Fixed
